[package]
name = "clearurl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["clearurl_bot"]
exclude = ["rules"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
url = "2.2"
anyhow = "1.0"
