["default"]
import = ""
rules = [
  "(?:%3F)?utm(?:_[a-z_]*)?",
  "(?:%3F)?ga_[a-z_]+",
  "(?:%3F)?yclid",
  "(?:%3F)?_openstat",
  "(?:%3F)?fb_action_(?:types|ids)",
  "(?:%3F)?fb_(?:source|ref)",
  "(?:%3F)?fbclid",
  "(?:%3F)?action_(?:object|type|ref)_map",
  "(?:%3F)?gs_l",
  "(?:%3F)?mkt_tok",
  "(?:%3F)?hmb_(?:campaign|medium|source)",
  "(?:%3F)?ref_?",
  "(?:%3F)?referrer",
  "(?:%3F)?gclid",
  "(?:%3F)?otm_[a-z_]*",
  "(?:%3F)?cmpid",
  "(?:%3F)?os_ehash",
  "(?:%3F)?_ga",
  "(?:%3F)?__twitter_impression",
  "(?:%3F)?wt_?z?mc",
  "(?:%3F)?wtrid",
  "(?:%3F)?[a-z]?mc",
  "(?:%3F)?dclid",
  "Echobox",
  "(?:%3F)?spm",
  "(?:%3F)?vn(?:_[a-z]*)+",
  "(?:%3F)?tracking_source",
  "(?:%3F)?ceneo_spo",
]
should_redirect = false
match_sub = false

["twitter.com"]
import = ""
rules = ["(?:ref_?)?src", "s", "cn", "ref_url", "t"]
should_redirect = false
match_sub = true


["m.bilibili.com"]
import = ""
match_sub = false
should_redirect = false
rules = ["bbid", "ts"]

["live.bilibili.com"]
import = ""
match_sub = false
should_redirect = false
rules = ["visit_id", "session_id", "broadcast_type", "is_room_feed"]

["www.bilibili.com"]
import = ""
rules = [
  "callback",
  "spm_id_from",
  "from_source",
  "from",
  "seid",
  "share_source",
  "msource",
  "refer_from",
  "share_medium",
  "share_source",
  "share_plat",
  "share_tag",
  "share_session_id",
  "timestamp",
  "unique_k",
  "-Arouter",
]
should_redirect = false
match_sub = false

["api.bilibili.com"]
import = ""
rules = []
should_redirect = false
match_sub = false

["b23.tv"]
import = "bilibili.com"
rules = []
should_redirect = true
match_sub = false

["www.amazon.com"]
import = ""
rules = [
  "p[fd]_rd_[a-z]*",
  "qid",
  "srs?",
  "__mk_[a-z]{1,3}_[a-z]{1,3}",
  "spIA",
  "ms3_c",
  "[a-z%0-9]*ie",
  "refRID",
  "colii?d",
  "[^a-z%0-9]adId",
  "qualifier",
  "_encoding",
  "smid",
  "field-lbr_brands_browse-bin",
  "ref_?",
  "th",
  "sprefix",
  "crid",
  "keywords",
  "cv_ct_[a-z]+",
  "linkCode",
  "creativeASIN",
  "ascsubtag",
  "aaxitk",
  "hsa_cr_id",
  "sb-ci-[a-z]+",
  "rnid",
  "dchild",
  "camp",
  "creative",
  "s",
]
match_sub = true
should_redirect = false

["youtube.com"]
import = ""
rules = ["feature", "gclid", "kw"]
match_sub = false
should_redirect = false

["reddit.com"]
import = ""
match_sub = false
should_redirect = false
rules = [
  "%24deep_link",
  "\\$deep_link",
  "correlation_id",
  "ref_campaign",
  "ref_source",
  "%243p",
  "\\$3p",
  "%24original_url",
  "\\$original_url",
  "_branch_match_id",
]

["bing.com"]
import = ""
match_sub = true
should_redirect = false
rules = ["cvid", "form", "sk", "sp", "sc", "qs", "qp"]

["twitch.com"]
import = ""
match_sub = true
should_redirect = false
rules = ["tt_medium", "tt_content"]

["smzdm.com"]
import = ""
match_sub = true
should_redirect = false
rules = ["zdm_ss", "from"]

["post.m.smzdm.com"]
import = "smzdm.com"
match_sub = false
should_redirect = false
rules = []

["taobao.com"]
import = ""
match_sub = false
should_redirect = false
rules = [
  "price",
  "sourceType",
  "suid",
  "ut_sk",
  "un",
  "share_crt_v",
  "sp_tk",
  "cpp",
  "shareurl",
  "short_name",
  "app",
  "scm[_a-z-]*",
  "pvid",
  "algo_expid",
  "algo_pvid",
  "ns",
  "abbucket",
  "ali_refid",
  "ali_trackid",
  "acm",
  "utparam",
  "pos",
  "abtest",
  "trackInfo",
  "utkn",
  "scene",
  "mytmenu",
  "turing_bucket",
  "lygClk",
  "impid",
  "bftTag",
  "bftRwd",
  "spm",
  "_u",
]

["item.taobao.com"]
import = "taobao.com"
match_sub = false
should_redirect = false
rules = []

["maimai.cn"]
import = ""
match_sub = false
should_redirect = false
rules = ["src", "share_channel"]

["jd.com"]
import = ""
match_sub = false
should_redirect = false
# clean all
rules = [".*"]

["item.m.jd.com"]
import = ""
match_sub = false
should_redirect = false
# clean all
rules = [".*"]

["i-item.jd.com"]
import = ""
match_sub = false
should_redirect = false
# clean all
rules = [".*"]

# this data is for test only
["_test"]
import = "default"
rules = ["_field1", "_field2"]
should_redirect = true
match_sub = true
