["default"]
import = ""
rules = []
should_redirect = false
match_sub = false

["twitter.com"]
import = ""
rules = [
  "(?:ref_?)?src",
  "s",
  "cn",
  "ref_url",
  "t"
]
should_redirect = false
match_sub = true

["www.bilibili.com"]
import = ""
rules = [
    "callback",
    "spm_id_from",
    "from_source",
    "from",
    "seid",
    "share_source",
    "msource",
    "refer_from",
    "share_medium",
    "share_source",
    "share_plat",
    "share_tag",
    "share_session_id",
    "timestamp",
    "unique_k"
]
should_redirect = false
match_sub = false

["b23.tv"]
import = "bilibili.com"
rules = []
should_redirect = true
match_sub = false



# this data is for test only
["_test"]
import = "default"
rules = [
  "_field1",
  "_field2",
]
should_redirect = true
match_sub = true

